forgot and reset password done
anees-rehman-brainx/todo-app-frontend pull request #1
Opened 2023-04-14 13:04 UTC by anees-rehman-brainx

2023-04-14 13:15 UTC, ali-faiz-brainx requested changes

2023-04-14 13:15 UTC, ali-faiz-brainx commented on src/components/AddTodo/AddTodo.jsx
> +       if(todoId !== 0 && subscribed){
the condition should be !todo instead of todo !===0

2023-04-14 13:15 UTC, ali-faiz-brainx commented on src/services/userService.js
> +            `${API_URL}/user/reset_password/${id}/${token}`,
pass token in headers instead of query param [Security reasons]

2023-04-14 13:15 UTC, ali-faiz-brainx commented on src/components/ResetPassword.jsx
> +    const passwordRegex = /^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{8,}$/
use password regex from constant files, So it makes reusable in other components also if needed.

2023-04-17 11:01 UTC, merged

2023-04-23 18:16 UTC, ali-iqbal-brainx commented on src/components/AddTodo/AddTodo.jsx
> +        subscribed = true;
component should be subscribed=false on unmount(need to revisit your logic)

2023-04-23 18:16 UTC, ali-iqbal-brainx commented on src/components/ForgotPassword.jsx
> +    let subscribed = true;
use state instead of local variables

2023-04-23 18:17 UTC, ali-iqbal-brainx commented on src/components/ForgotPassword.jsx
> +          <button type="submit" className="btn btn-primary w-50 mx-auto my-2 fw-bold" onClick={handleSubmit}>
span component on multiple lines if it contains more than one attribute

2023-04-23 18:18 UTC, ali-iqbal-brainx commented on src/components/ResetPassword.jsx
> +    let subscribed = true;
use state instead of local variables

2023-04-23 18:18 UTC, ali-iqbal-brainx commented on src/components/ResetPassword.jsx
> +          <button type="submit" className="btn btn-primary w-50 mx-auto my-2 fw-bold" onClick={handleSubmit}>
span component on multiple lines

2023-04-23 18:19 UTC, ali-iqbal-brainx commented on src/components/TodoList.jsx/TodoList.jsx
> +    let subscribed = true;
use state here

2023-04-23 18:21 UTC, ali-iqbal-brainx reviewed
-component should be subscribed=false on unmount(need to revisit your logic)
-use state instead of local variables
-span component on multiple lines if it contains more than one attribute